"use strict";
exports.__esModule = true;
var Product_1 = require("./Product");
var ProductService_1 = require("./ProductService");
var _productService = new ProductService_1.ProductService();
var result;
result = _productService.getById(2);
var resultList = _productService.getProducts();
console.log("Result:");
console.log(result);
console.log("resultList:");
console.log(resultList);
var p = new Product_1.Product();
p.name = "I Phone 8";
p.price = 5000;
p.category = "Telefon";
_productService.saveProduct(p);
console.log("result list'e eklendi");
console.log(resultList);
_productService.deleteProduct(_productService.getById(3));
console.log("result list'den silindi");
console.log(resultList);
p.price = 6000;
p.category = "TelefonGuncel";
console.log("result list güncellendi");
console.log(resultList);
